name: 'Prune lambda version'
description: 'Prune lambda workflow by cloudformation stack name'
author: 'Jun'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  RETAIN_FUNCTION_VERSION:
    description: 'Number of lambda function version to retain'
    required: false
  RETAIN_LAYER_VERSION:
    description: 'Number of lambda layer version to retain'
    required: false
  REGION:
    description: 'Your aws region'
    required: true
  ACCESS_KEY_ID:
    description: 'Your aws access key id'
    required: true
  SECRET_ACCESS_KEY:
    description: 'Your aws secret access key'
    required: true
  STACK_NAME:
    description: 'Your cloudformation stack name'
    required: true

runs:
  using: node20
  main: dist/index.js

  using: composite
  steps:
    - name: Package Installation
      run: |
        RETAIN_FUNCTION_VERSION="${{ inputs.RETAIN_FUNCTION_VERSION }}"
        RETAIN_LAYER_VERSION="${{ inputs.RETAIN_LAYER_VERSION }}"
        REGION="${{ inputs.REGION }}"
        ACCESS_KEY_ID="${{ inputs.ACCESS_KEY_ID }}"
        SECRET_ACCESS_KEY="${{ inputs.SECRET_ACCESS_KEY }}"
        STACK_NAME="${{ inputs.STACK_NAME }}"
        cd ./clean-lambda && \
        RETAIN_FUNCTION_VERSION="${RETAIN_FUNCTION_VERSION}" \
        RETAIN_LAYER_VERSION="${RETAIN_LAYER_VERSION}" \
        REGION="${REGION}" \
        ACCESS_KEY_ID="${ACCESS_KEY_ID}" \
        SECRET_ACCESS_KEY="${SECRET_ACCESS_KEY}" \
        STACK_NAME="${STACK_NAME}" \
        yarn install && npx ts-node ./index.ts
      shell: bash