name: 'Prune lambda version'
description: 'Prune lambda workflow by cloudformation stack name'
author: 'Jun'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  RETAIN_FUNCTION_VERSION:
    description: 'Number of lambda function version to retain'
    required: false
  RETAIN_LAYER_VERSION:
    description: 'Number of lambda layer version to retain'
    required: false
  REGION:
    description: 'Your aws region'
    required: true
  ACCESS_KEY_ID:
    description: 'Your aws access key id'
    required: true
  SECRET_ACCESS_KEY:
    description: 'Your aws secret access key'
    required: true
  STACK_NAME:
    description: 'Your cloudformation stack name'
    required: true

runs:
  using: composite
  steps:
    - name: Package Installation
      run: yarn install --cwd ./clean-lambda
      shell: bash

    - name: Run clean lambda
      env:
        RETAIN_LAYER_VERSION: ${{ inputs.RETAIN_LAYER_VERSION }}
        STACK_NAME: "${{ inputs.STACK_NAME }}"
        ACCESS_KEY_ID: ${{ inputs.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ inputs.SECRET_ACCESS_KEY }}
        # AWS_SESSION_TOKEN: ${{ inputs.AWS_SESSION_TOKEN }}
        REGION: ${{ inputs.REGION }}
      run: npx ts-node ./clean-lambda
      shell: bash
