name: 1Release Talent Management Report Fn
on:
    # push:
    #     branches: [master]
    workflow_dispatch:

jobs:
    deploy-to-sandbox:
        strategy:
            fail-fast: false
            matrix:
                env:
                    - sandbox-sg
                    - sandbox-de
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/wc-deploy-to-env.yml
        with:
            environment: ${{ matrix.env }}
        secrets: inherit
