name: Test clean lambda
on:
    workflow_dispatch:
        inputs:
            environment:
                required: true
                description: Environment to deploy
                default: sandbox
                type: environment
            STACK_NAME:
                required: true
                description: Stack Name
                type: string
            RETAIN_FUNCTION_VERSION:
                required: true
                description: Number of versions to retain
                type: string
                default: "3"

jobs:
    clean-lambda-test:
        runs-on: ubuntu-latest
        steps:
            - name: Setup AWS Credentials
              uses: junhuito/prune-lambda-version@v0.0.3
              with:
                  RETAIN_FUNCTION_VERSION: ${{ inputs.RETAIN_FUNCTION_VERSION }}
                  STACK_NAME: ${{ inputs.STACK_NAME }}
                  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  REGION: ${{ vars.AWS_REGION }}

