name: Test clean lambda v2
on:
    workflow_dispatch:
        inputs:
            environment:
                required: true
                description: Environment to deploy
                default: sandbox
                type: environment
            STACK_NAME:
                required: true
                description: Stack Name
                type: string
            RETAIN_FUNCTION_VERSION:
                required: false
                description: Number of versions to retain
                type: string
                default: "3"
            RETAIN_LAYER_VERSION:
                required: false
                description: Number of versions to retain
                type: string
                default: "3"

jobs:
    test-action:
        name: GitHub Actions Test
        runs-on: ubuntu-latest
        environment:
          name: ${{ inputs.environment }}

        steps:
          - name: Checkout
            id: checkout
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: ./clean-lambda/
            with:
                STACK_NAME: ${{ inputs.STACK_NAME }}
                REGION: ${{ vars.AWS_REGION }}
                ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                RETAIN_FUNCTION_VERSION: ${{ inputs.RETAIN_FUNCTION_VERSION }}
                RETAIN_LAYER_VERSION: ${{ inputs.RETAIN_LAYER_VERSION }}